const isVideo = p => /\.(mp4|mov|webm)$/i.test(p);
const seq = (dir, prefix, from, to, ext, width = 2, omit = []) => Array.from({length: to - from + 1}, (_, i) => i + from).filter(n => !omit.includes(n)).map(n => `${dir}/${prefix}${String(n).padStart(width, '0')}.${ext}`);
const make = (title, category, summary, role, tools, files) => ({title, category, summary, role, tools, videos: files.filter(isVideo), images: files.filter(f => !isVideo(f))});
const poster = (dir, name) => Array.from({length: 8}, (_, i) => `${dir}/${name} (${i + 1}).jpg`);

const projects = [
  make('粮仓','ip','围绕地域文化与品牌记忆建立的园区 IP 与视觉系统。','概念策划、IP 视觉、包装与应用延展','Illustrator / Photoshop / InDesign',seq('IP、品牌设计/1、粮仓','粮仓_',1,39,'jpg')),
  make('HEAVEN','ip','以未来感与极简语言建立的品牌与 IP 视觉系统。','视觉方向、IP 形象与品牌应用','Illustrator / Photoshop',seq('IP、品牌设计/2、HEAVEN/HEAVEN品牌','HEAVEN-',1,99,'jpg')),
  make('马上腾龙','ip','围绕角色、场景与传播应用展开的 IP 视觉项目。','角色视觉与场景应用','Illustrator / Photoshop',['IP、品牌设计/3、马上腾龙/1.png',...seq('IP、品牌设计/3、马上腾龙','马上腾龙ppt10.17_',1,50,'jpg',2,[2])]),
  make('不止于辣','ip','将感官记忆转化为年轻鲜明的品牌视觉语言。','主视觉、图形系统与品牌应用','Illustrator / Photoshop',seq('IP、品牌设计/4、不止于辣','',1,21,'png',1)),
  make('九曲黄河阵','ip','从中国神话人物与传统符号中提炼的当代 IP 叙事。','IP 视觉、角色设计、动态与应用延展','Photoshop / Illustrator / Procreate',[...seq('IP、品牌设计/5、九曲黄河阵','',1,6,'jpg',1),'IP、品牌设计/5、九曲黄河阵/黄龙真人.jpg','IP、品牌设计/5、九曲黄河阵/雷震子.jpg','IP、品牌设计/5、九曲黄河阵/老子.jpg','IP、品牌设计/5、九曲黄河阵/姜子牙.jpg','IP、品牌设计/5、九曲黄河阵/二郎神.jpg','IP、品牌设计/5、九曲黄河阵/三霄娘娘.jpg','IP、品牌设计/5、九曲黄河阵/视频/黄龙1_0000.mp4','IP、品牌设计/5、九曲黄河阵/视频/雷.mp4','IP、品牌设计/5、九曲黄河阵/视频/辽宁省朝阳市谢杖子村乡村振兴文化服务设计.mp4','IP、品牌设计/5、九曲黄河阵/视频/3_0000_1.mp4','IP、品牌设计/5、九曲黄河阵/视频/2.1.mp4','IP、品牌设计/5、九曲黄河阵/视频/1_0000_1.mp4','IP、品牌设计/5、九曲黄河阵/视频/1_0000.mp4']),
  make('紫金1号','ip','在产品气质与品牌识别之间建立的视觉表达。','视觉策略、主视觉与应用物料设计','Illustrator / Photoshop',['IP、品牌设计/6、紫金1号/1.png',...seq('IP、品牌设计/6、紫金1号','',2,8,'jpg',1)]),
  make('玉兔兔','ip','以亲和力和记忆点为核心构建的角色形象系统。','角色形象设计、视觉系统与应用延展','Illustrator / Photoshop',seq('IP、品牌设计/7、玉兔兔','',1,5,'png',1)),
  make('芭莎女孩','ip','以人物形象和色彩语言建立的媒介传播视觉。','IP 视觉方向、人物与应用稿输出','Illustrator / Photoshop',seq('IP、品牌设计/8、芭莎女孩','芭莎女孩',1,3,'png',1)),
  make('本草物语','brand','将传统药草文化转化为现代消费语境中的包装系统。','包装策划、主视觉和结构表达','Illustrator / Photoshop / CAD',seq('产品、包装设计/1、本草物语','',1,7,'png',1)),
  make('春和景明','brand','强调仪式感、节庆氛围与品牌辨识度的礼盒包装设计。','包装结构与视觉方案设计','Photoshop / Illustrator / CAD',seq('产品、包装设计/2、春和景明','春和景明·四方盘礼盒设计_',1,26,'jpg')),
  make('古井贡酒','brand','结合传统酒文化与现代审美的高辨识包装视觉。','包装视觉方案与应用延展','Photoshop / Illustrator',['产品、包装设计/3、古井贡酒/0.png',...seq('产品、包装设计/3、古井贡酒','',1,10,'png',1)]),
  make('辽遇芳华','brand','以器物文化与礼赠场景为起点的高端礼盒系统。','包装视觉设计与礼盒表达','Illustrator / Photoshop',[...seq('产品、包装设计/4、辽遇芳华','辽遇芳华·鸳鸯壶礼盒设计_',1,26,'jpg'),'产品、包装设计/4、辽遇芳华/视频展示.MP4']),
  make('昆仑关','brand','融合地域历史与产品气质的包装视觉方案。','包装视觉与应用物料输出','Illustrator / Photoshop',seq('产品、包装设计/5、昆仑关','',1,3,'png',1)),
  make('忆岩壹茶','brand','把茶饮的自然气息融入现代包装语言。','包装设计与视觉输出','Illustrator / Photoshop',['产品、包装设计/6、忆岩壹茶/忆岩壹茶_画板 1.png',...seq('产品、包装设计/6、忆岩壹茶','忆岩壹茶-',2,5,'png')]),
  make('颂莳卫生巾','brand','面向消费品市场，兼顾功能信息与品牌人格的包装表达。','包装视觉策略、主视觉与应用稿','Illustrator / Photoshop',seq('产品、包装设计/7、颂莳卫生巾包装设计','颂莳卫生巾包装设计_',1,21,'jpg')),
  make('GCRI 空气净化器','brand','以科技感和产品功能为核心的产品包装系统。','包装视觉与应用物料设计','Illustrator / Photoshop',seq('产品、包装设计/8、GCRI空气净化器','',1,16,'png',1)),
  make('GIGGLE 顽笑潮流运动场','media','以运动、速度与节奏激活现场体验的空间媒体内容。','动态内容策划、画面编排与空间媒体设计','After Effects / Premiere / Photoshop',[...['0.mp4','1.mp4','2.mp4','4.mp4','5.mp4','6.mp4','7.mp4','8.mp4'].map(x=>`媒体设计/1、GIGGLE顽笑潮流运动场/${x}`),'媒体设计/1、GIGGLE顽笑潮流运动场/平面/1.jpg','媒体设计/1、GIGGLE顽笑潮流运动场/平面/2.jpg',...Array.from({length:14},(_,i)=>`媒体设计/1、GIGGLE顽笑潮流运动场/平面/GIGGLE-5_画板 1 副本 ${i+2}.jpg`)]),
  make('左庭右院','media','面向空间与情绪表达的短片视觉项目。','视觉节奏设计、视频剪辑与表现','After Effects / Premiere',['媒体设计/2、左庭右院/compressO-视频1.mp4']),
  make('D² + T² = EVERYONE²','media','以图像编排和视觉叙事表达多元身份与共同体概念。','概念视觉、图像编辑与版式设计','Photoshop / Illustrator / After Effects',['媒体设计/3、D²＋T²=EVERYONE²/D²＋T²=EVERYONE²/jpg文件/001.png','媒体设计/3、D²＋T²=EVERYONE²/D²＋T²=EVERYONE²/jpg文件/002.png','媒体设计/3、D²＋T²=EVERYONE²/D²＋T²=EVERYONE²/jpg文件/003.png','媒体设计/3、D²＋T²=EVERYONE²/D²＋T²=EVERYONE²/jpg文件/004.jpg','媒体设计/3、D²＋T²=EVERYONE²/D²＋T²=EVERYONE²/jpg文件/005.jpg','媒体设计/3、D²＋T²=EVERYONE²/D²＋T²=EVERYONE²/jpg文件/006.jpg','媒体设计/3、D²＋T²=EVERYONE²/D²＋T²=EVERYONE²/jpg文件/007logo及主题字_画板 1.jpg','媒体设计/3、D²＋T²=EVERYONE²/D²＋T²=EVERYONE²/jpg文件/视频.mp4']),
  make('扎西德勒','media','将文化意象转化为平面、动态与展示空间中的连续体验。','视觉概念、海报、动态与展示内容设计','Photoshop / Illustrator / After Effects',[...poster('媒体设计/4、扎西德勒/平面海报1','静态海报'),...poster('媒体设计/4、扎西德勒/平面海报2','平面海报'),...['金鱼.mp4','莲花.mp4','盘长.mp4','白盖.mp4','法轮.mp4','法螺.mp4','宝瓶.mp4','宝伞.mp4'].map(x=>`媒体设计/4、扎西德勒/动态海报/${x}`),'媒体设计/4、扎西德勒/交互与展示/展示视频.mp4','媒体设计/4、扎西德勒/交互与展示/交互展示.mp4']),
  make('E-secret','media','以短片形式表达情绪与概念，兼具视觉张力与叙事节奏。','视觉节奏、剪辑与动态表达','After Effects / Premiere',['媒体设计/5、E-secret/《E-secret》.mp4','媒体设计/5、E-secret/关键帧 .jpg']),
  make('The Original Senses','media','围绕感官体验展开的沉浸式动态视觉表达。','动态视觉与内容呈现','After Effects / Premiere / Photoshop',['媒体设计/6、The Original Senses/《The Original Senses》.mp4','媒体设计/6、The Original Senses/关键帧.jpg']),
  make('绿洲计划','media','以环境与成长为主题形成具有引导感的视觉系统。','视觉策划、平面与内容编排','Photoshop / Illustrator',seq('媒体设计/7、绿洲计划','',1,20,'png',1)),
  make('日行记','media','把日常观察转化为可被观看与回味的时间叙事。','视频创作、画面编排与视觉叙事','After Effects / Premiere / Photoshop',['媒体设计/8、日行记/日行记.MP4',...seq('媒体设计/8、日行记','',1,3,'png',1)])
];
const labels={ip:'IP 视觉',brand:'品牌 / 包装',media:'媒体 / 动态'};
const grid=document.querySelector('#worksGrid'),dialog=document.querySelector('#projectDialog'),content=document.querySelector('#dialogContent');let category='all',media='all';
const element=(file,alt,card=false,poster='')=>isVideo(file)?card?`<video muted loop playsinline preload="none"${poster?` poster="${poster}"`:''} data-src="${file}" aria-label="${alt}"></video>`:`<video controls preload="metadata" playsinline aria-label="${alt}"><source src="${file}" type="video/mp4"></video>`:`<img src="${file}" alt="${alt}" loading="lazy">`;
const previewIO=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target;if(e.isIntersecting){if(!v.getAttribute('src'))v.src=v.dataset.src;v.play().catch(()=>{})}else v.pause()}),{rootMargin:'250px'});
function render(){const visible=projects.filter(p=>(category==='all'||p.category===category)&&(media==='all'||p[`${media}s`].length));grid.innerHTML=visible.map((p,n)=>{const preview=media==='video'?p.videos[0]:media==='image'?p.images[0]:p.videos[0]||p.images[0];const count=`${p.videos.length?`${p.videos.length} 视频`:''}${p.videos.length&&p.images.length?' · ':''}${p.images.length?`${p.images.length} 图片`:''}`;return `<article class="project-card ${n===0&&media==='all'?'project-card-featured':''}"><button class="project-open" type="button" data-project="${projects.indexOf(p)}" aria-label="查看 ${p.title} 项目详情"><div class="project-media">${element(preview,p.title,true,p.images[0]||'')}<span class="project-index">${String(n+1).padStart(2,'0')}</span>${p.videos.length?'<span class="video-chip">VIDEO</span>':''}</div><div class="project-info"><p>${labels[p.category]}</p><h3>${p.title}</h3><span>${count}<br>查看项目 ↗</span></div></button></article>`}).join('');previewIO.disconnect();document.querySelectorAll('.project-media video[data-src]').forEach(v=>previewIO.observe(v))}
const section=(title,files,p)=>files.length?`<section class="asset-section"><div class="asset-section-title"><h3>${title}</h3><span>${files.length} 项内容</span></div><div class="dialog-gallery ${title==='视频作品'?'video-gallery':''}">${files.map(f=>`<figure>${element(f,`${p.title} ${title}`)}</figure>`).join('')}</div></section>`:'';
function open(i){const p=projects[i];content.innerHTML=`<div class="dialog-head"><p>${labels[p.category]} / FULL PROJECT</p><h2 id="dialogTitle">${p.title}</h2><p class="dialog-summary">${p.summary}</p></div><div class="dialog-meta"><div><span>个人分工</span><p>${p.role}</p></div><div><span>使用工具</span><p>${p.tools}</p></div></div>${section('视频作品',p.videos,p)}${section('图片作品',p.images,p)}`;dialog.showModal();document.body.classList.add('dialog-open')}
document.querySelector('.filters').onclick=e=>{const b=e.target.closest('.filter');if(!b)return;category=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()};document.querySelector('.content-switcher').onclick=e=>{const b=e.target.closest('.media-filter');if(!b)return;media=b.dataset.media;document.querySelectorAll('.media-filter').forEach(x=>x.classList.toggle('active',x===b));render()};grid.onclick=e=>{const b=e.target.closest('[data-project]');if(b)open(+b.dataset.project)};document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};dialog.onclose=()=>document.body.classList.remove('dialog-open');const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-nav');toggle.onclick=()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.textContent=open?'CLOSE':'MENU'};nav.onclick=()=>{nav.classList.remove('open');toggle.textContent='MENU'};render();
document.querySelectorAll('a[href="#top"]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();window.scrollTo({top:0,behavior:'smooth'})}));
